spring:
  application.name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          url-expression: "'http://'+serviceId"
    kubernetes:
      reload:
        enabled: true
        mode: polling
        period: 5000
      discovery:
        filter: "metadata.labels['s1p']"